CREATE TABLE "polar_subscription" (
	"id" serial PRIMARY KEY NOT NULL,
	"polar_id" text NOT NULL,
	"polar_created_at" timestamp with time zone NOT NULL,
	"polar_modified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"status" text NOT NULL,
	"amount" integer NOT NULL,
	"currency" text NOT NULL,
	"recurring_interval" text NOT NULL,
	"recurring_interval_count" integer NOT NULL,
	"current_period_start" timestamp with time zone NOT NULL,
	"current_period_end" timestamp with time zone,
	"trial_start" timestamp with time zone,
	"trial_end" timestamp with time zone,
	"started_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"cancel_at_period_end" boolean DEFAULT false NOT NULL,
	"canceled_at" timestamp with time zone,
	"customer_cancellation_reason" text,
	"customer_cancellation_comment" text,
	"polar_customer_id" text NOT NULL,
	"polar_product_id" text NOT NULL,
	"polar_discount_id" text,
	"polar_checkout_id" text,
	"seats" integer,
	"prices" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"meters" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"discount" jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"custom_field_data" jsonb,
	CONSTRAINT "polar_subscription_polarId_unique" UNIQUE("polar_id")
);
--> statement-breakpoint
ALTER TABLE "polar_subscription" ADD CONSTRAINT "polar_subscription_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "polar_subscription" ADD CONSTRAINT "polar_subscription_product_id_polar_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."polar_product"("id") ON DELETE no action ON UPDATE no action;