CREATE TABLE "polar_order" (
	"id" serial PRIMARY KEY NOT NULL,
	"polar_id" text NOT NULL,
	"polar_created_at" timestamp with time zone NOT NULL,
	"polar_modified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" integer NOT NULL,
	"product_id" integer NOT NULL,
	"subscription_id" integer,
	"status" text NOT NULL,
	"paid" boolean DEFAULT false NOT NULL,
	"billing_reason" text NOT NULL,
	"subtotal_amount" integer NOT NULL,
	"discount_amount" integer NOT NULL,
	"net_amount" integer NOT NULL,
	"tax_amount" integer NOT NULL,
	"total_amount" integer NOT NULL,
	"applied_balance_amount" integer NOT NULL,
	"due_amount" integer NOT NULL,
	"refunded_amount" integer NOT NULL,
	"refunded_tax_amount" integer NOT NULL,
	"platform_fee_amount" integer NOT NULL,
	"currency" text NOT NULL,
	"billing_name" text,
	"billing_address" jsonb,
	"invoice_number" text NOT NULL,
	"is_invoice_generated" boolean DEFAULT false NOT NULL,
	"polar_customer_id" text NOT NULL,
	"polar_product_id" text NOT NULL,
	"polar_subscription_id" text,
	"polar_discount_id" text,
	"polar_checkout_id" text,
	"seats" integer,
	"description" text NOT NULL,
	"items" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"discount" jsonb,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"custom_field_data" jsonb,
	CONSTRAINT "polar_order_polarId_unique" UNIQUE("polar_id")
);
--> statement-breakpoint
ALTER TABLE "polar_order" ADD CONSTRAINT "polar_order_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "polar_order" ADD CONSTRAINT "polar_order_product_id_polar_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."polar_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "polar_order" ADD CONSTRAINT "polar_order_subscription_id_polar_subscription_id_fk" FOREIGN KEY ("subscription_id") REFERENCES "public"."polar_subscription"("id") ON DELETE no action ON UPDATE no action;